//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8669
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="Hisense", ConfigurationName="HSIOEC_SkuPluSoap")]
public interface HSIOEC_SkuPluSoap
{
    
    // CODEGEN: 命名空间 Hisense 的元素名称 inJsonPara 以后生成的消息协定未标记为 nillable
    [System.ServiceModel.OperationContractAttribute(Action="Hisense/GetSkuPlu", ReplyAction="*")]
    GetSkuPluResponse GetSkuPlu(GetSkuPluRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetSkuPluRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSkuPlu", Namespace="Hisense", Order=0)]
    public GetSkuPluRequestBody Body;
    
    public GetSkuPluRequest()
    {
    }
    
    public GetSkuPluRequest(GetSkuPluRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="Hisense")]
public partial class GetSkuPluRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string inJsonPara;
    
    public GetSkuPluRequestBody()
    {
    }
    
    public GetSkuPluRequestBody(string inJsonPara)
    {
        this.inJsonPara = inJsonPara;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetSkuPluResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSkuPluResponse", Namespace="Hisense", Order=0)]
    public GetSkuPluResponseBody Body;
    
    public GetSkuPluResponse()
    {
    }
    
    public GetSkuPluResponse(GetSkuPluResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="Hisense")]
public partial class GetSkuPluResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetSkuPluResult;
    
    public GetSkuPluResponseBody()
    {
    }
    
    public GetSkuPluResponseBody(string GetSkuPluResult)
    {
        this.GetSkuPluResult = GetSkuPluResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface HSIOEC_SkuPluSoapChannel : HSIOEC_SkuPluSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class HSIOEC_SkuPluSoapClient : System.ServiceModel.ClientBase<HSIOEC_SkuPluSoap>, HSIOEC_SkuPluSoap
{
    
    public HSIOEC_SkuPluSoapClient()
    {
    }
    
    public HSIOEC_SkuPluSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HSIOEC_SkuPluSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HSIOEC_SkuPluSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HSIOEC_SkuPluSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetSkuPluResponse HSIOEC_SkuPluSoap.GetSkuPlu(GetSkuPluRequest request)
    {
        return base.Channel.GetSkuPlu(request);
    }
    
    public string GetSkuPlu(string inJsonPara)
    {
        GetSkuPluRequest inValue = new GetSkuPluRequest();
        inValue.Body = new GetSkuPluRequestBody();
        inValue.Body.inJsonPara = inJsonPara;
        GetSkuPluResponse retVal = ((HSIOEC_SkuPluSoap)(this)).GetSkuPlu(inValue);
        return retVal.Body.GetSkuPluResult;
    }
}
