//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8762
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="Hisense", ConfigurationName="HSIOEC_EtpEnterpriseSoap")]
public interface HSIOEC_EtpEnterpriseSoap
{
    
    // CODEGEN: 命名空间 Hisense 的元素名称 inJsonPara 以后生成的消息协定未标记为 nillable
    [System.ServiceModel.OperationContractAttribute(Action="Hisense/GetEnterprise", ReplyAction="*")]
    GetEnterpriseResponse GetEnterprise(GetEnterpriseRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetEnterpriseRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEnterprise", Namespace="Hisense", Order=0)]
    public GetEnterpriseRequestBody Body;
    
    public GetEnterpriseRequest()
    {
    }
    
    public GetEnterpriseRequest(GetEnterpriseRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="Hisense")]
public partial class GetEnterpriseRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string inJsonPara;
    
    public GetEnterpriseRequestBody()
    {
    }
    
    public GetEnterpriseRequestBody(string inJsonPara)
    {
        this.inJsonPara = inJsonPara;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetEnterpriseResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEnterpriseResponse", Namespace="Hisense", Order=0)]
    public GetEnterpriseResponseBody Body;
    
    public GetEnterpriseResponse()
    {
    }
    
    public GetEnterpriseResponse(GetEnterpriseResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="Hisense")]
public partial class GetEnterpriseResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetEnterpriseResult;
    
    public GetEnterpriseResponseBody()
    {
    }
    
    public GetEnterpriseResponseBody(string GetEnterpriseResult)
    {
        this.GetEnterpriseResult = GetEnterpriseResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface HSIOEC_EtpEnterpriseSoapChannel : HSIOEC_EtpEnterpriseSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class HSIOEC_EtpEnterpriseSoapClient : System.ServiceModel.ClientBase<HSIOEC_EtpEnterpriseSoap>, HSIOEC_EtpEnterpriseSoap
{
    
    public HSIOEC_EtpEnterpriseSoapClient()
    {
    }
    
    public HSIOEC_EtpEnterpriseSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HSIOEC_EtpEnterpriseSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HSIOEC_EtpEnterpriseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HSIOEC_EtpEnterpriseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetEnterpriseResponse HSIOEC_EtpEnterpriseSoap.GetEnterprise(GetEnterpriseRequest request)
    {
        return base.Channel.GetEnterprise(request);
    }
    
    public string GetEnterprise(string inJsonPara)
    {
        GetEnterpriseRequest inValue = new GetEnterpriseRequest();
        inValue.Body = new GetEnterpriseRequestBody();
        inValue.Body.inJsonPara = inJsonPara;
        GetEnterpriseResponse retVal = ((HSIOEC_EtpEnterpriseSoap)(this)).GetEnterprise(inValue);
        return retVal.Body.GetEnterpriseResult;
    }
}
