//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8669
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="Hisense", ConfigurationName="HSIOEC_SkuPluExSoap")]
public interface HSIOEC_SkuPluExSoap
{
    
    // CODEGEN: 命名空间 Hisense 的元素名称 inJsonPara 以后生成的消息协定未标记为 nillable
    [System.ServiceModel.OperationContractAttribute(Action="Hisense/GetSkuPluEx", ReplyAction="*")]
    GetSkuPluExResponse GetSkuPluEx(GetSkuPluExRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetSkuPluExRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSkuPluEx", Namespace="Hisense", Order=0)]
    public GetSkuPluExRequestBody Body;
    
    public GetSkuPluExRequest()
    {
    }
    
    public GetSkuPluExRequest(GetSkuPluExRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="Hisense")]
public partial class GetSkuPluExRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string inJsonPara;
    
    public GetSkuPluExRequestBody()
    {
    }
    
    public GetSkuPluExRequestBody(string inJsonPara)
    {
        this.inJsonPara = inJsonPara;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetSkuPluExResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSkuPluExResponse", Namespace="Hisense", Order=0)]
    public GetSkuPluExResponseBody Body;
    
    public GetSkuPluExResponse()
    {
    }
    
    public GetSkuPluExResponse(GetSkuPluExResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="Hisense")]
public partial class GetSkuPluExResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetSkuPluExResult;
    
    public GetSkuPluExResponseBody()
    {
    }
    
    public GetSkuPluExResponseBody(string GetSkuPluExResult)
    {
        this.GetSkuPluExResult = GetSkuPluExResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface HSIOEC_SkuPluExSoapChannel : HSIOEC_SkuPluExSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class HSIOEC_SkuPluExSoapClient : System.ServiceModel.ClientBase<HSIOEC_SkuPluExSoap>, HSIOEC_SkuPluExSoap
{
    
    public HSIOEC_SkuPluExSoapClient()
    {
    }
    
    public HSIOEC_SkuPluExSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HSIOEC_SkuPluExSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HSIOEC_SkuPluExSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HSIOEC_SkuPluExSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetSkuPluExResponse HSIOEC_SkuPluExSoap.GetSkuPluEx(GetSkuPluExRequest request)
    {
        return base.Channel.GetSkuPluEx(request);
    }
    
    public string GetSkuPluEx(string inJsonPara)
    {
        GetSkuPluExRequest inValue = new GetSkuPluExRequest();
        inValue.Body = new GetSkuPluExRequestBody();
        inValue.Body.inJsonPara = inJsonPara;
        GetSkuPluExResponse retVal = ((HSIOEC_SkuPluExSoap)(this)).GetSkuPluEx(inValue);
        return retVal.Body.GetSkuPluExResult;
    }
}
